---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: navidrome
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: ./clusters/xs4/kube/media/navidrome
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  info:
    - name: 'Project:'
      value: "https://www.navidrome.org/"
