---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: vikunja
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: ./clusters/xs4/kube/dashboard/vikunja
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
    syncOptions:
    - CreateNamespace=true
  info:
    - name: 'Project:'
      value: "https://vikunja.io/"