---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: minecraft-server
  name: minecraft-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.80.30"
spec:
  ports:
    - port: 25565
      targetPort: 25565
  selector:
    app: minecraft-server
  type: LoadBalancer
