---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minecraft-server
  name: minecraft-server
spec:
  replicas: 1
  serviceName: minecraft-server
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: mc
          image: itzg/minecraft-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: ENABLE_AUTOPAUSE
              value: "TRUE"
            - name: AUTOPAUSE_TIMEOUT_INIT
              value: "30"
            - name: AUTOPAUSE_TIMEOUT_EST
              value: "10"
            - name: MAX_TICK_TIME
              value: "-1"
            - name: MOTD
              value: "Greenfields Worlds"
            - name: sync-chunk-writes
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: minecraft-data
          readinessProbe:
            exec:
              command:
                - mc-health
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 18
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-storage
