---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "replicated"
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
